Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Shopping_Cart.Infrastructure;
using Shopping_Cart.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Shopping_Cart.Controllers
{
    public class PagesController : Controller
    {
        private readonly ShoppingCartContext context;

        public PagesController(ShoppingCartContext context)
        {
            this.context = context;
        }

        // GET / or /slug
        public async Task<IActionResult> Page(string slug)
        {
            if (slug == null)
            {
                return View(await context.Pages.Where(x => x.Slug == "home").FirstOrDefaultAsync());
            }

            Page page = await context.Pages.Where(x => x.Slug == slug).FirstOrDefaultAsync();

            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }
    }
}

Infrastructure/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_Cart.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shopping_Cart.Infrastructure
{
    public class CategoriesViewComponent : ViewComponent
    {
        private readonly ShoppingCartContext context;

        public CategoriesViewComponent(ShoppingCartContext context)
        {
            this.context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await GetCategoriesAsync();
            return View(categories);
        }

        private Task<List<Category>> GetCategoriesAsync()
        {
            return context.Categories.OrderBy(x => x.Sorting).ToListAsync();
        }
    }
}

Infrastructure/MainMenuViewComponent.cs
using Shopping_Cart.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shopping_Cart.Infrastructure
{
    public class MainMenuViewComponent : ViewComponent
    {
        private readonly ShoppingCartContext context;

        public MainMenuViewComponent(ShoppingCartContext context)
        {
            this.context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var pages = await GetPagesAsync();
            return View(pages);
        }

        private Task<List<Page>> GetPagesAsync()
        {
            return context.Pages.OrderBy(x => x.Sorting).ToListAsync();
        }
    }
}

Infrastructure/SmallCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Shopping_Cart.Models;
using System.Collections.Generic;
using System.Linq;

namespace Shopping_Cart.Infrastructure
{
    public class SmallCartViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<CartItem> cart = HttpContext.Session.GetJson<List<CartItem>>("Cart");
            SmallCartViewModel smallCartVM;

            if(cart ==null || cart.Count == 0)
            {
                smallCartVM = null;
            }
            else
            {
                smallCartVM = new SmallCartViewModel
                {
                    NumberOfItems = cart.Sum(x => x.Quantity),
                    TotalAmount = cart.Sum(x => x.Quantity * x.Price)
                };
            }

            return View(smallCartVM);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopping_Cart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shopping_Cart</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 justify-conten-end">
                        @if(User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Edit" class="btn btn-primary">My Account</a>
                            </li>
                            <li class="nav-item ml-1">
                                <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Hi, @User.Identity.Name, Logout</a>
                            </li>
                            @if(User.IsInRole("Admin") || User.IsInRole("Editor"))
                            {
                                <li class="nav-item ml-1">
                                    <a asp-area="Admin" asp-controller="Pages" asp-action="Index" class="btn btn-success">Admin Area</a>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Login" class="btn btn-success">Login</a>
                            </li>
                            <li class="nav-item ml-1">
                                <a asp-controller="Account" asp-action="Register" class="btn btn-primary">Register</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        @await Component.InvokeAsync("MainMenu")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            <div class="row">
                <div class="col-3">
                    @await Component.InvokeAsync("Categories")

                    <div class="smallcart bg-success mt-3 p-3 text-white">
                        @await Component.InvokeAsync("SmallCart")
                    </div>
                </div>
                <div class="col">
                    @RenderBody()
                </div>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Shopping_Cart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
	<div class="alert alert-success notification">
		@TempData["Success"]
	</div>
}

@if (TempData["Error"] != null)
{
	<div class="alert alert-danger notification">
		@TempData["Error"]
	</div>
}